# ---------- ETAPA DE COMPILACIÓN ----------
FROM ubuntu:24.04 AS builder

RUN apt-get update && \
    apt-get install -y openjdk-21-jdk && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY HolaDocker.java .

RUN javac HolaDocker.java


# ---------- ETAPA DE EJECUCIÓN ----------
FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y openjdk-21-jre && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/HolaDocker.class .

ENTRYPOINT ["java", "HolaDocker"]